# -*- coding: utf-8 -*-
"""Codetech 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l82Lon1fcc01Tz7uMMvW5qhPwxpI4iZv
"""

# Install necessary libraries
!pip install transformers torch --quiet

from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch

model_name = "gpt2"  # You can also use "gpt2-medium", "gpt2-large" if needed
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = GPT2LMHeadModel.from_pretrained(model_name)

# Set device (GPU if available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

# Function to generate text
def generate_text(prompt, max_length=200):
    inputs = tokenizer.encode(prompt, return_tensors="pt").to(device)
    outputs = model.generate(
        inputs,
        max_length=max_length,
        num_return_sequences=1,
        no_repeat_ngram_size=2,
        top_k=50,
        top_p=0.95,
        temperature=0.7,
        do_sample=True,
        early_stopping=True
    )
    generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return generated_text

# User prompt
user_prompt = input("Enter a topic or prompt: ")

# Generate and print text
generated_paragraph = generate_text(user_prompt)
print("\nGenerated Text:\n")
print(generated_paragraph)

